//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid TaskID { get; set; }
        public System.Guid ProjectID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid PriorityID { get; set; }
        public System.Guid StatusID { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
